export const ENDPOINTS = {
   GET_USER: '/user',
  UPDATE_USER: '/user/update',
  GET_SLOTS: '/slots',
  UPLOAD_VIDEO: '/video/upload',
  SUBMIT_REVIEW: '/video/submit',
  GET_SUBJECTS: '/subjects',
  GET_PROFILE: '/profile',
  SUBMIT_VERIFICATION: '/profile/submit',
  GET_DOCUMENTS: '/documents',
  GET_INTERVIEW: '/interview',
  JOIN_INTERVIEW: '/interview/join',
  GET_VERIFICATION_STATUS: '/verification/status',
  GET_REJECTION_STATUS: '/application/rejection',
  REAPPLY: '/application/reapply',
  CREATE_STUDENT_PROFILE: '/student/profile',
  GET_PLANS: '/plans',
  START_TRIAL: '/subscription/trial',
};

